definitions:
  bunker-web_routers_openapi_user.GetStatusResponseData:
    properties:
      create_at:
        description: 创建时间
        type: integer
      expire_at:
        description: 有效期至
        type: integer
      game_id:
        description: 绑定的游戏ID
        type: integer
      is_admin:
        description: 是否为系统管理员
        type: boolean
      slots:
        description: Slots 列表
        items:
          $ref: '#/definitions/bunker-web_routers_openapi_user.Slot'
        type: array
      unlimited_until:
        description: 无限制权限截止时间
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  bunker-web_routers_openapi_user.RedeemRequest:
    properties:
      redeem_code:
        description: 要使用的兑换码
        type: string
      username:
        description: 用户名
        minLength: 1
        type: string
    type: object
  bunker-web_routers_openapi_user.Slot:
    properties:
      expire_at:
        description: Slots 有效期至
        type: integer
      game_id:
        description: Slots 绑定的游戏ID
        type: integer
      note:
        description: Slots 备注
        type: string
    type: object
  g79.RentalServerInfo:
    properties:
      capacity:
        type: integer
      chainInfo:
        type: string
      entity_id:
        type: string
      has_pwd:
        type: string
      icon_index:
        type: integer
      image_url:
        type: string
      ip_address:
        type: string
      like_num:
        type: integer
      mc_version:
        type: string
      min_level:
        type: string
      name:
        type: string
      offset:
        description: unknown type
      owner_id:
        type: integer
      player_count:
        type: integer
      pvp:
        type: boolean
      server_name:
        type: string
      server_type:
        type: string
      status:
        type: integer
      visibility:
        type: integer
      world_id:
        type: string
    type: object
  giner.BasicResponse:
    properties:
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  helper.GetUserDetailsRequest:
    properties:
      uid:
        description: 目标玩家的启动器UID
        minimum: 1
        type: integer
    type: object
  helper.GetUserDetailsResponse:
    properties:
      data:
        items:
          additionalProperties: {}
          type: object
        type: array
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  helper.GetUserStateRequest:
    properties:
      uid:
        description: 目标玩家的启动器UID
        minimum: 1
        type: integer
    type: object
  helper.GetUserStateResponse:
    properties:
      data:
        additionalProperties: {}
        type: object
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  helper.SearchUserRequest:
    properties:
      nickname:
        description: 要查找的玩家昵称
        minLength: 1
        type: string
    type: object
  helper.SearchUserResponse:
    properties:
      data:
        items:
          additionalProperties: {}
          type: object
        type: array
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  rental_server.BanPlayerRequest:
    properties:
      server_id:
        description: 租赁服实体ID
        minLength: 1
        type: string
      status:
        description: 是否为黑名单状态 (0, 1)
        enum:
        - 0
        - 1
        type: integer
      uid:
        description: 目标玩家的启动器UID
        minimum: 1
        type: integer
    type: object
  rental_server.CreateBackupRequest:
    properties:
      backup_name:
        description: 备份名称
        minLength: 1
        type: string
      backup_slot:
        description: 要使用的备份槽位, 范围为1-5
        maximum: 5
        minimum: 1
        type: integer
      server_code:
        description: 服务器号
        minLength: 1
        type: string
    type: object
  rental_server.GetPlayerListRequest:
    properties:
      is_online:
        description: 是否在线 (false, true, null(不限))
        type: boolean
      length:
        description: 查询分页长度 (null(不限))
        example: 50
        type: integer
      offset:
        description: 查询分页偏移
        type: integer
      order_type:
        description: 排序类型 (0, 1)
        type: integer
      server_id:
        description: 租赁服实体ID
        minLength: 1
        type: string
      status:
        description: 玩家状态 (是否黑名单) (0, 1, null(不限))
        type: integer
    type: object
  rental_server.GetPlayerListResponse:
    properties:
      data:
        items:
          additionalProperties: {}
          type: object
        type: array
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  rental_server.KickPlayerRequest:
    properties:
      server_id:
        description: 租赁服实体ID
        minLength: 1
        type: string
      uid:
        description: 目标玩家的启动器UID
        minimum: 1
        type: integer
    type: object
  rental_server.SearchRequest:
    properties:
      server_name:
        description: 要查找的租赁服号
        minLength: 1
        type: string
    type: object
  rental_server.SearchResponse:
    properties:
      data:
        $ref: '#/definitions/g79.RentalServerInfo'
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  rental_server.SetLevelLimitationRequest:
    properties:
      level:
        description: 要设置的服务器准入等级, 0为关闭, 最高为50(基岩V)
        maximum: 50
        minimum: 0
        type: integer
      server_code:
        description: 服务器号
        minLength: 1
        type: string
    type: object
  rental_server.SetPasswordRequest:
    properties:
      password:
        description: 要设置的服务器密码, 内容为空则代表关闭密码
        type: string
      server_code:
        description: 服务器号
        minLength: 1
        type: string
    type: object
  rental_server.SetVisibilityRequest:
    properties:
      server_code:
        description: 服务器号
        minLength: 1
        type: string
      visibility:
        description: 要设置的公开性, 0为所有人可见, 1为好友可见, 2为私密
        maximum: 2
        minimum: 0
        type: integer
    type: object
  rental_server.TurnOffRequest:
    properties:
      server_code:
        description: 服务器号
        minLength: 1
        type: string
    type: object
  rental_server.TurnOnRequest:
    properties:
      server_code:
        description: 服务器号
        minLength: 1
        type: string
    type: object
  user.GetStatusResponse:
    properties:
      data:
        $ref: '#/definitions/bunker-web_routers_openapi_user.GetStatusResponseData'
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  user.RedeemResponse:
    properties:
      data:
        $ref: '#/definitions/user.RedeemResponseData'
      message:
        description: 成功或失败原因
        type: string
      success:
        description: 是否成功
        type: boolean
    type: object
  user.RedeemResponseData:
    properties:
      result:
        description: 兑换结果
        type: string
    type: object
info:
  contact: {}
  description: BunkerWeb OpenAPI document, feel free to contact us if you have any
    questions or suggestions.
  title: BunkerWeb OpenAPI
paths:
  /openapi/helper/get_user_details:
    post:
      consumes:
      - application/json
      description: |-
        通过uid获取玩家详细信息, 需要提供 API key
        注意: 此 API 会尝试进行游戏登录 (Helper)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/helper.GetUserDetailsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/helper.GetUserDetailsResponse'
      summary: 获取玩家详细信息
      tags:
      - 玩家
  /openapi/helper/get_user_state:
    post:
      consumes:
      - application/json
      description: |-
        通过uid获取玩家状态信息, 例如主页点击数量, 需要提供 API key
        注意: 此 API 会尝试进行游戏登录 (Helper)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/helper.GetUserStateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/helper.GetUserStateResponse'
      summary: 获取玩家状态信息
      tags:
      - 玩家
  /openapi/helper/rental_server/get_player_list:
    post:
      consumes:
      - application/json
      description: |-
        获取租赁服玩家列表, 例如历史进入列表, 需要提供 API key
        注意: 此 API 会尝试进行游戏登录 (Helper)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.GetPlayerListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/rental_server.GetPlayerListResponse'
      summary: 获取租赁服玩家列表
      tags:
      - 租赁服 (查询类)
  /openapi/helper/rental_server/search:
    post:
      consumes:
      - application/json
      description: |-
        查询租赁服基础信息, 需要提供 API key
        注意: 此 API 会尝试进行游戏登录 (Helper)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/rental_server.SearchResponse'
      summary: 查询租赁服信息
      tags:
      - 租赁服 (查询类)
  /openapi/helper/search_user:
    post:
      consumes:
      - application/json
      description: |-
        查询玩家, 可通过昵称来获取uid, 需要提供 API key
        注意: 此 API 会尝试进行游戏登录 (Helper)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/helper.SearchUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/helper.SearchUserResponse'
      summary: 查询玩家
      tags:
      - 玩家
  /openapi/owner/rental_server/ban_player:
    post:
      consumes:
      - application/json
      description: |-
        更新租赁服玩家黑名单状态, 游戏账号需要拥有指定的租赁服, 且需要提供 API key
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.BanPlayerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 更新租赁服玩家黑名单状态
      tags:
      - 租赁服 (管理类)
  /openapi/owner/rental_server/create_backup:
    post:
      consumes:
      - application/json
      description: |-
        为自己的服务器创建备份, 需要提供 API Key 且绑定游戏账号
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.CreateBackupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 创建服务器备份
      tags:
      - 租赁服 (管理类)
  /openapi/owner/rental_server/kick_player:
    post:
      consumes:
      - application/json
      description: |-
        踢出指定租赁服的指定玩家, 游戏账号需要拥有指定的租赁服, 且需要提供 API key
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.KickPlayerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 踢出租赁服玩家
      tags:
      - 租赁服 (管理类)
  /openapi/owner/rental_server/set_level_limitation:
    post:
      consumes:
      - application/json
      description: |-
        设置自己服务器的等级限制, 需要提供 API Key 且绑定游戏账号
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.SetLevelLimitationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 设置服务器等级限制
      tags:
      - 租赁服 (管理类)
  /openapi/owner/rental_server/set_password:
    post:
      consumes:
      - application/json
      description: |-
        设置自己服务器的密码, 需要提供 API Key 且绑定游戏账号
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.SetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 设置服务器密码
      tags:
      - 租赁服 (管理类)
  /openapi/owner/rental_server/set_visibility:
    post:
      consumes:
      - application/json
      description: |-
        设置自己服务器的公开性, 需要提供 API Key 且绑定游戏账号
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.SetVisibilityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 设置服务器公开性
      tags:
      - 租赁服 (管理类)
  /openapi/owner/rental_server/turn_off:
    post:
      consumes:
      - application/json
      description: |-
        关闭自己的服务器, 需要提供 API Key 且绑定游戏账号
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.TurnOffRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 关闭服务器
      tags:
      - 租赁服 (管理类)
  /openapi/owner/rental_server/turn_on:
    post:
      consumes:
      - application/json
      description: |-
        开启自己的服务器, 需要提供 API Key 且绑定游戏账号
        注意: 此 API 会尝试进行游戏登录 (Owner)
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/rental_server.TurnOnRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/giner.BasicResponse'
      summary: 开启服务器
      tags:
      - 租赁服 (管理类)
  /openapi/user/get_status:
    get:
      consumes:
      - application/json
      description: 用户信息查询, 需要提供 API Key
      parameters:
      - description: 此处需要填写 API Key, 可以从用户菜单获取
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/user.GetStatusResponse'
      summary: 用户信息查询
      tags:
      - 用户中心
  /openapi/user/redeem:
    post:
      consumes:
      - application/json
      description: 使用兑换码, 无需进行登录验证
      parameters:
      - description: 请求时需要在 Body 携带以下查询参数
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/bunker-web_routers_openapi_user.RedeemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功时返回
          schema:
            $ref: '#/definitions/user.RedeemResponse'
      summary: 使用兑换码
      tags:
      - 用户中心
swagger: "2.0"
